version: '3'
services:
  node:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    command: sh -c "cd next-app && npm run dev"
    ports:
      - "1234:1234"
